baseurl = "https://lxymahatma.github.io"
locale = "zh"

# For publishing pages in right time
timeZone = "Asia/Tokyo"

# Theme i18n support
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

[pagination]
    pagerSize = 6
