[en]
    languageDirection = "ltr"
    languageName = "English"
    title = "lxymahatma's blog"
    weight = 2

    [en.params]
        article.license.default = "Licensed under CC BY-NC-SA 4.0"
        sidebar.subtitle = "Posting random stuff"

[zh-cn]
    languageDirection = "ltr"
    languageName = "简体中文"
    title = "lxymahatma的博客"
    weight = 1

    [zh-cn.params]
        article.license.default = "使用 CC BY-NC-SA 4.0 协议"
        sidebar.subtitle = "随便摸鱼写写"
