# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# Bilibili
[[social]]
identifier = "bilibili"
name = "BiliBili"
url = "https://space.bilibili.com/255895683"

[social.params]
icon = "brand-bilibili"

# GitHub
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/lxymahatma"

[social.params]
icon = "brand-github"
