# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
favicon = "img/favicon.png"
rssFullContent = true

[footer]
    customText = ""
    since = 2024

[dateFormat]
    published = ":date_full"
    lastUpdated = ":date_medium"

[sidebar]
    avatar = "img/avatar.png"

[article]
    headingAnchor = false
    math = false
    readingTime = true

    [article.license]
        enabled = true

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    card = "summary_large_image"
    site = ""

[colorScheme]
    default = "auto"
    toggle = true

[imageProcessing.thumbnail]
    enabled = true

[imageProcessing.content]
    enabled = true

## Comments
[comments]
    enabled = true
    provider = "giscus"

    [comments.giscus]
        category = "Announcements"
        categoryID = "DIC_kwDOMI8xEs4CgF13"
        darkTheme = "dark"
        emitMetadata = 0
        lightTheme = "light"
        mapping = "pathname"
        reactionsEnabled = 1
        repo = "lxymahatma/lxymahatma.github.io"
        repoID = "R_kgDOMI8xEg"
